[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "0 14 * * *"
params = "batch=0&size=4&write=1"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "5 14 * * *"
params = "batch=1&size=4&write=1"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "10 14 * * *"
params = "batch=2&size=4&write=1"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "15 14 * * *"
params = "batch=3&size=4&write=1"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "20 14 * * *"
params = "batch=4&size=4&write=1"

[[scheduled.functions]]
name = "cron_jobs"
schedule = "25 14 * * *"
params = "batch=5&size=4&write=1"
